# Generated by Django 2.2.5 on 2023-08-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Cardio', 'Cardio'), ('Lower body', 'Lower body'), ('Upper Body and core', 'Upper Body and core'), ('Active rest and recovery', 'Active rest and recovery'), ('Lower body with a focus on glutes', 'Lower body with a focus on glutes'), ('Upper body', 'Upper body'), ('Rest and recovery', 'Rest and recovery')], max_length=60)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('cardio', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Cardio?')),
                ('cardio_duration', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[(' ', ' '), ('Back and Bis', 'Back and Bis'), ('Chest and Tris', 'Chest and Tris'), ('Quad Focused Legs', 'Quad Focused Legs'), ('Glute Focused Legs', 'Glute Focused Legs'), ('Shoulders', 'Shoulders'), ('Lower body', 'Lower body'), ('Upper Body and core', 'Upper Body and core'), ('Active rest and recovery', 'Active rest and recovery'), ('Lower body with a focus on glutes', 'Lower body with a focus on glutes'), ('Upper body', 'Upper body')], default=' ', max_length=60),
        ),
    ]
