# Generated by Django 2.2.5 on 2023-08-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutTracker', '0003_auto_20230816_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[(' ', ' '), ('Back and Bis', 'Back and Bis'), ('Chest and Tris', 'Chest and Tris'), ('Quad Focused Legs', 'Quad Focused Legs'), ('Glute Focused Legs', 'Glute Focused Legs'), ('Shoulders', 'Shoulders'), ('Lower body', 'Lower body'), ('Upper Body and core', 'Upper Body and core'), ('Active rest and recovery', 'Active rest and recovery'), ('Lower body with a focus on glutes', 'Lower body with a focus on glutes'), ('Upper body', 'Upper body')], max_length=60),
        ),
    ]
